# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NuGetToolInstaller@0


    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: ServiceNow-DevOps-Config-Agent-Upload-Config@1
      name: 'componentUpload'
      inputs:
        connectedServiceName: 'dev72220-Parts Unlimited-ServiceNow DevOps Service Connection'
        applicationName: 'Parts Unlimited'
        uploadTarget: 'component'
        configFile: '**/*.param.json'
        namePath: 'ARM'
        dataFormat: 'json'
        autoValidate: true
        autoCommit: true
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\*test*.dll
          !**\obj\**

        searchFolder: '$(System.DefaultWorkingDirectory)'
        vsTestVersion: '16.0'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    

    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)'
        Contents: '**/*.json'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'

- stage: Test
  jobs:
  - job: Validate
#    variables:
#      - name: varChangesetNumber
#        value: $[stageDependencies.Build.Build.outputs['componentUpload.changesetNumber'] ]

#    steps:    
#    - task: ServiceNow-DevOps-Config-Agent-Register-Pipeline@1
#      inputs:
#        connectedServiceName: 'glidefastconsultingllcdemo17-Parts Unlimited-ServiceNow DevOps Service Connection'
#        changesetNumber: '$(varChangesetNumber)'
#        applicationName: 'Parts Unlimited'

- stage: Deploy
  jobs:
  - job: Deploy_Application_Precondition
    pool: server
    steps:  

    - task: ServiceNow-DevOps-Server-Change-Acceleration@1
      inputs:
        connectedServiceName: 'dev72220-Parts Unlimited-ServiceNow DevOps Service Connection'
        changeRequestDetails: |
          {
                                "setCloseCode": false,
                                "attributes": {
                                  "requested_by": {
                                      "name": "System Administrator"
                                  },
                                  "category": "DevOps",
                                  "priority": "2",
                                  "comments": "This is a sample pipeline script to be added in your change step",
                                  "work_notes": "Update this to work_notes",
                                  "start_date": "2023-01-05 11:59:59",
                                  "end_date": "2023-01-08 11:59:59"
                               }
                              }


  - job: Deploy_Application
    dependsOn: Deploy_Application_Precondition
    condition: succeeded()