# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 4.5.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
                  - name: ServiceNow DevOps Change Automation
  # You may pin to the exact commit or the version.
  # uses: ServiceNow/servicenow-devops-change@373e092812580f05105089c20129e6efe347c8e5
  uses: ServiceNow/servicenow-devops-change@v4.0.0
  with:
    # ServiceNow Instance URL
    instance-url: 
    # Devops Integration User Name
    devops-integration-user-name: # optional
    # Devops Integration User Password
    devops-integration-user-password: # optional
    # Devops Integration Token
    devops-integration-token: # optional
    # Orchestration Tool Id
    tool-id: 
    # Display Name of the Job
    job-name: 
    # Github Context
    context-github: 
    # The max. time in seconds to wait until the action should fail.
    timeout: # optional, default is 3600
    # The time in seconds to wait between trying the API.
    interval: # optional, default is 100
    # The customized inputs to create change with the requested details.
    change-request: 
    # The max. time in seconds to wait until change created.
    changeCreationTimeOut: # optional, default is 3600
    # This value will be used to resume or abort the pipeline if the change is not created within the mentioned time period in changeCreationTimeOut. 
    abortOnChangeCreationFailure: # optional, default is true
    # This value will be used to resume or abort the pipeline after a timeout has occurred in case a change step is still in a pending state.
    abortOnChangeStepTimeout: # optional, default is true
    # The customized inputs to process deployment gate job related change.
    deployment-gate: # optional
          
